# .github/workflows/publish.yml
name: Publish to pub.dev (publish.yml)

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # tag pattern on pub.dev: 'v{{version}}'
    # branches: [ main ] # Enable this to test the workflow on every push

jobs:
  validate:
    name: Validate and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.47.0

      - run: flutter pub get

      # Quality checks
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos
      - run: flutter test

  publish:
    name: Publish to pub.dev
    needs: validate
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
