name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*' # only trigger on version tags like v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'stable'

      - name: Install dependencies
        run: flutter pub get
      
      - name: Analyze code (optional)
        run: dart analyze

      - name: Publish package
        env:
          PUB_DEV_ACCESS_TOKEN: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}
        run: |
          mkdir -p ~/.pub-cache
          cat > ~/.pub-cache/credentials.json <<EOF
          {
            "accessToken":"${PUB_DEV_ACCESS_TOKEN}",
            "refreshToken":"",
            "tokenEndpoint":"https://accounts.google.com/o/oauth2/token",
            "scopes":["https://www.googleapis.com/auth/userinfo.email","openid"],
            "expiration": 9999999999
          }
          EOF

          dart pub publish --force
