# .github/workflows/test.yml
name: Test and Quality Checks

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Dart
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 3.9.2

      # Install dependencies
      - run: flutter pub get
      
      # Quality checks
      - run: dart format --output=none --set-exit-if-changed .
      - run: dart analyze --fatal-infos
      - run: dart test
